### ISSUE TITLE
Error when i try to start the boilerplate

### ISSUE THREAD

**Issue by medzhidov** [contentful/contentful.php#265] opened 2019-03-23 15:42 UTC
```
Fatal error: Uncaught InvalidArgumentException: Unexpected field type "RichText" encountered while trying to format value. in C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php:419 Stack trace: #0 C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php(373): Contentful\Delivery\ResourceBuilder->formatValue(Object(Contentful\Delivery\ContentTypeField), Array, NULL) #1 C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php(356): Contentful\Delivery\ResourceBuilder->buildField(Object(Contentful\Delivery\ContentTypeField), Array, NULL) #2 C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php(296): Contentful\Delivery\ResourceBuilder->buildFields(Object(Contentful\Delivery\ContentType), Array, 'ru-RU', NULL) #3 C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php(159): Contentful\Delivery\ResourceBuilder->buildEntry(Array) #4 C:\OSPanel\domains in C:\OSPanel\domains\test.test\vendor\contentful\contentful\src\Delivery\ResourceBuilder.php on line 419
```

Before i tried to launch `contentful-laravel` and got an access token error, but i install right all tokens data in my .env file.

**Comment by dslpp056193** [comment] 2019-03-23 15:55
Boilerplate still does not work, but i delete "preview api token" and now laravel works fine.

**Comment by yadakhov** [comment] 2019-04-04 18:43
Hello.  Are you still having this issue?  I can assist you.  Which boilerplate are you referring to?

**Comment by pgrigoruta** [comment] 2019-11-25 17:50
The Laravel package looks to be installing correctly now, closing this as a cannot reproduce. @medzhidov feel free to add more details if you are still having issues.

**Closed by pgrigoruta** 2019-11-25 17:50 UTC
